# Vectorization

In [2]:
import math
import numpy as np
from sklearn.datasets import make_regression

In [18]:
x = np.mat('1.; 2.; 3')
p = 3

In [19]:
x

matrix([[ 1.],
        [ 2.],
        [ 3.]])

In [21]:
Phi = np.matrix(np.zeros([x.shape[0],p]))

In [29]:
Phi[]

matrix([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

In [14]:
for i in range(p):
    Phi[:, i] = np.power(x, i)

In [16]:
Phi[:, 1]

matrix([[ 1.],
        [ 2.],
        [ 3.]])

In [31]:
 test = np.mat('1., 2, 3; 4, 5, 6; 7, 8,9')
test 

matrix([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [32]:
#index rows and columns
test[1:2]

matrix([[ 4.,  5.,  6.]])

In [33]:
test[0:2]

matrix([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [34]:
test[0:3, 2]

matrix([[ 3.],
        [ 6.],
        [ 9.]])

In [36]:
test[0:2, 0:2]

matrix([[ 1.,  2.],
        [ 4.,  5.]])