In [1]:
from part1 import *
import numpy as np
import math

In [2]:
Xtest = np.mat([[0., 1.],
                [1., 0.],
                [2., 2.],
                [1., 1.]])

w = np.mat(' 0.5; -0.6')
b = 0.2

In [3]:
n = Xtest.shape[0]
Y = np.zeros(n)  # initialize as all zeros
P = np.mat(np.zeros((n, 1)))

In [4]:
Y

array([ 0.,  0.,  0.,  0.])

In [5]:
P 

matrix([[ 0.],
        [ 0.],
        [ 0.],
        [ 0.]])

In [6]:
P.shape

(4, 1)

In [7]:
Y.shape

(4,)

In [8]:
w

matrix([[ 0.5],
        [-0.6]])

In [9]:
for i, x in enumerate(Xtest):
    x = x.T
    z = compute_z(x, w, b)
    p = np.

[[-0.4]]
[[ 0.7]]
[[  5.55111512e-17]]
[[ 0.1]]
